### ISSUE TITLE
Can i add filter in the initial value

### ISSUE THREAD

**Issue by fusionx1** [fabio-looker/looker_sso_tool#6] opened 2018-03-15 03:17 UTC
Hi can i add filter in the initial value - https://github.com/fabio-looker/looker_sso_tool/blob/master/index.html#L174-L180 ?

Im trying to inject a filter so i can create a dynamic report.

**Comment by fabio-looker** [comment] 2018-03-21 22:25
Are you asking about changing the tool demonstrate the use of a filter, or as you just asking about how you would use SSO embed to pass a filter into a dashboard?

In the latter case, you just add it to the embed path, [like so](https://fabio-looker.github.io/looker_sso_tool/#o=(embed_path:/embed/looks/1%3FState%3DNY%26Date%3D28%2Bdays,external_user_id:'123',first_name:Testy,host:example.looker.com,last_name:McTestFace,models:thelook,permissions:!(access_data,see_looks),session_length:600))

![image](https://user-images.githubusercontent.com/23034640/37740734-30d3b504-2d35-11e8-82d9-78e2f66cccd2.png)

**Comment by fabio-looker** [comment] 2018-03-27 15:50
Closing until the issue is clarified

**Closed as completed by fabio-looker** 2018-03-27 15:50 UTC
